### ISSUE TITLE
소셜 로그인 후처리 프로세스 구현 & 에러핸들링 코드 리팩토링

### ISSUE THREAD

**Issue by BellWin98** [TEAM-PIN-UP/BE-PIN-UP#35]
## 📄 이슈 내용

1. 소셜 로그인 후 닉네임, 프로필사진, 약관동의 등록
2. 엔티티가 없거나, 이미 있는 경우의 예외 처리 공통화

## 📝 작업 상세 내용

- [x] 소셜 로그인 후처리 API 개발
- [x] EntityNotFound, EntityAlreadyExist 클래스 생성 및 기존 불필요 클래스 삭제

**Comment by kwonyonghyun** [comment]
수고하셨습니다!!
